# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0004_remove_user_course'),
        ('courses', '0002_auto_20160813_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loginreg.User')),
            ],
        ),
    ]
